commandSql_datasource=Az adatforr\u00E1s
commandSql_description=Egyszer\u0171 SQL fel\u00FClet biztos\u00EDt\u00E1sa a be\u00E1ll\u00EDtott adatforr\u00E1shoz.
databaseDatasourceTypeName=adatb\u00E1zis
exceptionCouldNotExecuteStmt=Lek\u00E9rdez\u00E9s nem hajthat\u00F3 v\u00E9gre\: {0}
exceptionCouldNotOpenDatasource=Nem siker\u00FClt megnyitni az adatforr\u00E1st\: {0}
exceptionCouldNotPrepareStmt=Lek\u00E9rdez\u00E9st nem lehetett el\u0151k\u00E9sz\u00EDteni\: {0}
